apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: webkonce-service-monitor
  namespace: default
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: webkonce
  endpoints:
    - port: web
      interval: 30s
  namespaceSelector:
    matchNames:
      - default