apiVersion: apps/v1
kind: Deployment
metadata:
  name: webkonce
  labels:
    app: webkonce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webkonce
  template:
    metadata:
      labels:
        app: webkonce
    spec:
      containers:
        - name: webkonce
          image: 921283598378.dkr.ecr.us-east-1.amazonaws.com/lambda-nestjs-repo
          imagePullPolicy: Always
          ports:
            - containerPort: 3000